name: dental_disease_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.0
  intl: ^0.19.0         
  photo_view: ^0.15.0


  dio: ^5.7.0
  flutter_form_builder: ^9.2.0
  form_builder_validators: ^10.0.0
  flutter_secure_storage: ^9.2.2
  fluttertoast: ^8.2.8
  go_router: ^14.2.0   # for role-based navigation
  image_picker: ^1.0.7
  url_launcher: ^6.1.14
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    # Or if you want to include the whole folder:
    # - assets/
